
/* SESSION */
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_ERROR = 'LOG_IN_ERROR'

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT'
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const LOG_OUT_ERROR = 'LOG_OUT_ERROR'

export const REQUEST_LOGGED_IN_USER = 'REQUEST_LOGGED_IN_USER'
export const GET_LOGGED_IN_USER_SUCCESS = 'GET_LOGGED_IN_USER_SUCCESS'
export const GET_LOGGED_IN_USER_ERROR = 'GET_LOGGED_IN_USER_ERROR'

/* TWEETS */
export const REQUEST_TWEETS = 'REQUEST_TWEETS'
export const LOAD_TWEETS_SUCCESS = 'LOAD_TWEETS_SUCCESS'
export const LOAD_TWEETS_ERROR = 'LOAD_TWEETS_ERROR'

export const REQUEST_POST_TWEET = 'REQUEST_POST_TWEET'
export const POST_TWEET_SUCCESS = 'POST_TWEET_SUCCESS'
export const POST_TWEET_ERROR = 'POST_TWEET_ERROR'

export const REQUEST_DELETE_TWEET = 'REQUEST_DELETE_TWEET'
export const DELETE_TWEET_SUCCESS = 'DELETE_TWEET_SUCCESS'
export const DELETE_TWEET_ERROR = 'DELETE_TWEET_ERROR'

/* USERS */
export const REQUEST_USERS = 'REQUEST_USERS'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_ERROR = 'LOAD_USERS_ERROR'

export const REQUEST_FOLLOW_USER = 'REQUEST_FOLLOW_USER'
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS'
export const FOLLOW_USER_ERROR = 'FOLLOW_USER_ERROR'

export const REQUEST_UNFOLLOW_USER = 'REQUEST_UNFOLLOW_USER'
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS'
export const UNFOLLOW_USER_ERROR = 'UNFOLLOW_USER_ERROR'
